### ISSUE TITLE
Add an Example of Model Controller Service Project

### ISSUE THREAD

**Issue by Nisha-Rao21** [Kuwarsaab/Learn-Spring-Framework#6]
A simple project showcasing Backend Services is designed in most industries. It implements all CRUD operations performed on a Friend Collection System using a Model Controller Service architecture using Java and Spring Boot. Multiple annotations will be introduced in this, which will enhance learning.

@Kuwarsaab Please let me know if I can contribute this project for Hacktoberfest 2024.

**Comment by Kuwarsaab** [comment]
Yes, You can contribute.
